version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/changepermission.sh
      timeout: 3600
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: scripts/status_apache.sh
      timeout: 3600
      runas: ec2-user
